In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./data/relatorio_vendas.csv")
df.sample(5)

,data_pedido,modo_envio,nome_cliente,segmento_cliente,cidade,estado,regiao,departamento,tipo_produto,vendas,quantidade,lucro
5728,2017-10-25,Envio rápido,Lucas Gonçalves,B2B,Campina Grande,Paraíba,Nordeste,Materiais de construção,ferramentas,1544.52,8,-250.99
2473,2016-06-09,Entrega padrão,João Guilherme Costela,B2C,Fortaleza,Ceará,Nordeste,Materiais de construção,ferramentas,1990.88,3,248.86
2143,2019-02-11,Envio rápido,Natália da Costa,B2C,Boa Vista,Roraima,Norte,Jardinagem e paisagismo,pesticidas,78.61,4,38.52
5554,2019-09-12,24 horas,Augusto da Cruz,B2C,Fortaleza,Ceará,Nordeste,Jardinagem e paisagismo,pesticidas,242.35,11,116.33
770,2019-12-01,Econômica,Nicolas Rezende,B2B,São Paulo,São Paulo,Sudeste,Materiais de construção,ferramentas,4225.86,5,892.13

In [3]:
df.data_pedido = pd.to_datetime(df.data_pedido)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   data_pedido       8940 non-null   datetime64[ns]
 1   modo_envio        8940 non-null   object
 2   nome_cliente      8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   cidade            8940 non-null   object
 5   estado            8940 non-null   object
 6   regiao            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_produto      8940 non-null   object
 9   vendas            8940 non-null   float64
 10  quantidade        8940 non-null   int64
 11  lucro             8940 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 838.3+ KB

## Time de Vendas

> **Top 10 clientes por total em Vendas**

In [5]:
df_cliente_vendas = df.groupby("nome_cliente")["vendas"].sum().nlargest(10).copy()
df_cliente_vendas = df_cliente_vendas.reset_index()
df_cliente_vendas

            nome_cliente    vendas
0    Maria Luiza Almeida  64777.54
1        Ana Julia Pinto  51398.95
2            Ryan Farias  48178.94
3         Heitor da Mata  47610.85
4  Maria Clara Gonçalves  46946.42
5         Raquel Freitas  44826.26
6             Davi Ramos  43769.21
7            Amanda Melo  42354.27
8         Alexia Ribeiro  41238.84
9         Calebe Ribeiro  41056.70

In [6]:
df_cliente_vendas.columns = ["Clientes", "Vendas"]

# Col Auxiliar
df_cliente_vendas["Ranque"] = df_cliente_vendas.index + 1
df_cliente_vendas = df_cliente_vendas.set_index("Ranque")
display(df_cliente_vendas)

                     Clientes    Vendas
Ranque
1         Maria Luiza Almeida  64777.54
2             Ana Julia Pinto  51398.95
3                 Ryan Farias  48178.94
4              Heitor da Mata  47610.85
5       Maria Clara Gonçalves  46946.42
6              Raquel Freitas  44826.26
7                  Davi Ramos  43769.21
8                 Amanda Melo  42354.27
9              Alexia Ribeiro  41238.84
10             Calebe Ribeiro  41056.70

In [7]:
table_top10 = df_cliente_vendas.style
table_top10

In [8]:
print(type(table_top10))

<class 'pandas.io.formats.style.Styler'>

In [9]:
# Formatação R$

table_top10.format(
    {"Vendas": "R$ {:,.2f}"}
)
table_top10