In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./data/relatorio_vendas.csv")

In [3]:
df.sample(5)

,data_pedido,modo_envio,nome_cliente,segmento_cliente,cidade,estado,regiao,departamento,tipo_produto,vendas,quantidade,lucro
5428,2018-11-23,Entrega padrão,Samuel Nascimento,B2C,Belo Horizonte,Minas Gerais,Sudeste,Jardinagem e paisagismo,sementes,7.10,1,2.31
971,2019-01-22,Entrega padrão,Juan Teixeira,B2B,Santo André,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,121.67,7,-97.33
3486,2019-12-08,Envio rápido,Vitor Gabriel Santos,B2C,Belford Roxo,Rio de Janeiro,Sudeste,Automotivo,ferramentas automotivas,435.15,2,87.03
5715,2019-05-15,Envio rápido,Larissa da Conceição,B2C,Belo Horizonte,Minas Gerais,Sudeste,Jardinagem e paisagismo,pesticidas,163.04,3,55.02
1348,2019-08-19,Entrega padrão,Davi Lucca Silveira,B2C,Belém,Pará,Norte,Jardinagem e paisagismo,ferramentas de jardinagem,22.93,4,-38.98

In [4]:
df.data_pedido = pd.to_datetime(df.data_pedido)

display(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   data_pedido       8940 non-null   datetime64[us]
 1   modo_envio        8940 non-null   str
 2   nome_cliente      8940 non-null   str
 3   segmento_cliente  8940 non-null   str
 4   cidade            8940 non-null   str
 5   estado            8940 non-null   str
 6   regiao            8940 non-null   str
 7   departamento      8940 non-null   str
 8   tipo_produto      8940 non-null   str
 9   vendas            8940 non-null   float64
 10  quantidade        8940 non-null   int64
 11  lucro             8940 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(1), str(8)
memory usage: 838.3 KB

None

## Time de Vendas

> **Top 10 clientes por total em Vendas**

In [5]:
df_cliente_vendas = df.groupby("nome_cliente")["vendas"].sum().nlargest(10).copy()
df_cliente_vendas = df_cliente_vendas.reset_index()
display(df_cliente_vendas)

            nome_cliente    vendas
0    Maria Luiza Almeida  64777.54
1        Ana Julia Pinto  51398.95
2            Ryan Farias  48178.94
3         Heitor da Mata  47610.85
4  Maria Clara Gonçalves  46946.42
5         Raquel Freitas  44826.26
6             Davi Ramos  43769.21
7            Amanda Melo  42354.27
8         Alexia Ribeiro  41238.84
9         Calebe Ribeiro  41056.70

In [6]:
df_cliente_vendas.columns = ["Clientes", "Vendas"]

# Col Auxiliar
df_cliente_vendas["Ranque"] = df_cliente_vendas.index + 1
df_cliente_vendas = df_cliente_vendas.set_index("Ranque")

display(df_cliente_vendas)

                     Clientes    Vendas
Ranque
1         Maria Luiza Almeida  64777.54
2             Ana Julia Pinto  51398.95
3                 Ryan Farias  48178.94
4              Heitor da Mata  47610.85
5       Maria Clara Gonçalves  46946.42
6              Raquel Freitas  44826.26
7                  Davi Ramos  43769.21
8                 Amanda Melo  42354.27
9              Alexia Ribeiro  41238.84
10             Calebe Ribeiro  41056.70

In [7]:
table_top10 = df_cliente_vendas.style
table_top10

In [8]:
# Tipo 
print(type(table_top10))

<class 'pandas.io.formats.style.Styler'>

In [9]:
# Formatação R$

table_top10.format(
    {"Vendas": "R$ {:,.2f}"} 
)
table_top10

## 02 - Destacando Elementos

O total ganho em vendas e o total ganho em lucros a partir dos tipos de produtos vendidos.

In [10]:
df_venda_lucro = df.groupby("tipo_produto")[["vendas", "lucro"]].sum()
df_venda_lucro.index.name = "tipo produto"
df_venda_lucro

                               vendas      lucro
tipo produto
decoração de jardim          82680.87   19880.86
encanamentos                373224.39  -11243.39
equipamentos de limpeza     542304.55   17448.30
ferramentas                 995159.43   82042.91
ferramentas automotivas     502109.33  126660.54
ferramentas de jardinagem   648880.47  106408.80
fertilizantes                53144.55   22509.86
iluminação                  275229.82   40531.09
materiais de paisagismo     150552.80   -3823.67
materiais de revestimento   629656.41  -57737.23
mobiliário de exterior      328932.37   53569.57
mudas                         8811.69    2762.88
pesticidas                  244958.41  106688.03
peças de reposição          486907.88  182297.32
pneus                      1022430.50  134923.09
sementes                     39980.49   17730.06
vasos                       696045.39   67887.28

In [11]:
# Criando objeto style
table_venda_lucro = df_venda_lucro.style

In [12]:
table_venda_lucro.format("R${:,.2f}")
table_venda_lucro.highlight_max(color="green").highlight_min(color="#F16165")

### Background em Gradiente

In [13]:
table_venda_lucro.background_gradient(cmap="Greens")

In [14]:
# ---
#  Estilização em CSS
# 
#   Seletor ==> parte da tabela a ser transformada (th -- table header)
#   Propriedades 

#  table_styles: 'dict[Any, CSSStyles] | CSSStyles | None'

table_styles = dict(
    selector="th",
    props="font-weight: bold; font-family: Arial; text-align: left; text-transform: capitalize;"
)
table_venda_lucro.set_table_styles([table_styles], overwrite=False)